The goal is to use matrix for encryption and decryption. We can use a matrix as an encryption key and it's inverse matrix as decryption 
key. In the following post illustrate the process. 

In [1]:
import numpy as np

In [2]:
ak = np.matrix = [ [2,1], [3,2]]  # Encryption key

In [3]:
dk = np.matrix= [ [2, -1], [-3, 2] ] # Decryption key

In [4]:
# Each character will represent with numbers as follows
repres_num = { 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13,
     'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, ' ': 27}

In [5]:
# Following is our plaintext message
plain_text = 'prepare to negotiate'

In [6]:
# Let's represent our plain_text with corresponding number value
# We will create list with number values
# Then we will create numpy array and will reshape according to our need
# as our Encryption matrix is 2 x 2. So we need to create 2 x n matrix in order 
# generate encrypted matrix by multiplying with the encryption key

hold = []
for i in plain_text:
    hold.append(repres_num[i])
trans = np.asarray(hold).reshape(2, len(hold)//2)

In [7]:
trans

array([[16, 18,  5, 16,  1, 18,  5, 27, 20, 15],
       [27, 14,  5,  7, 15, 20,  9,  1, 20,  5]])

In [8]:
cipher = np.dot(ak, trans)

In [9]:
cipher  # this is our cipher text matrix

array([[ 59,  50,  15,  39,  17,  56,  19,  55,  60,  35],
       [102,  82,  25,  62,  33,  94,  33,  83, 100,  55]])

In [10]:
# we can decrypt with the decryption key
decipher = np.dot(dk, cipher)

In [11]:
decipher

array([[16, 18,  5, 16,  1, 18,  5, 27, 20, 15],
       [27, 14,  5,  7, 15, 20,  9,  1, 20,  5]])

In [12]:
# Above we got back our original translated palintext matrix.
# we can get back the plain text using the dictionary we created 
dec = decipher.ravel().tolist()

In [13]:
dec

[16, 18, 5, 16, 1, 18, 5, 27, 20, 15, 27, 14, 5, 7, 15, 20, 9, 1, 20, 5]

In [14]:
PT = ""
for i in dec:
    PT += list(repres_num.keys())[list(repres_num.values()).index(i)]
    

In [15]:
PT

'prepare to negotiate'